### ISSUE TITLE
Not stacked

### ISSUE THREAD

**Issue by jinman** [Skn0tt/mui-datatables-responsive-demo#1]
@Skn0tt, love your example. Is there any way we can do a card view using Customrowrender that is not stacked and can work in non-responsive mode. We would like to render rows as "cards" side by side like a gridlist and have both "card view" and "list view" that works in non-responsive mode. Any ideas will help. Will flexbox work? Really appreciate your help

**Comment by Skn0tt** [comment]
Hi @jinman. This repo is meant to demonstrate the particular feature request implemented in https://github.com/gregnb/mui-datatables/pull/589. Maybe pay their docs a visit, a lot has changed since I last worked with that library :)
